name: Setup python environment
description: Checkout, setup python, install dependencies and cache pip

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python-version}}
        cache: "pip"
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
