name: "Staged CI Pipelines"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install flake8
        run: pip install flake8
      - name: Linting with flake8
        run: flake8 day4/app

  test:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: pip install -r day4/requirements.txt
      - name: Testing Code
        run: pytest day4/tests/ > logs/test_output.txt
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-log-py-${{matrix.python-version}}
          path: logs/test_output.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: "Packaging artifacts"
        run: |
          mkdir -p dist
          zip dist/my_app.zip scripts/
      - uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() && success() && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: my_app
      - name: "Upload artifacts to Release or Deploy"
        run: echo "This is where we upload the zip to release or deploy"
