name: "Staged CI Pipelines"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-environment
        with:
          python-version: "3.11"
      - name: Install flake8
        run: pip install flake8
      - name: Linting with flake8
        run: flake8 scripts/
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-environment
        with:
          python-version: ${{matrix.python-version}}
      - name: Testing Code
        run: pytest tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-environment
        with:
          python-version: "3.11"
      - name: "Packaging artifacts"
        run: |
          mkdir -p dist
          zip dist/my_app.zip scripts/
      - uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-environment
        with:
          python-version: "3.11"
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: my_app
      - name: "Upload artifacts to Release or Deploy"
        run: echo "This is where we upload the zip to release or deploy"
