name: "Day 3 Chaining"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  chaining_processes:
    name: "Chaining Processes"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          echo "Running flake8"
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: false

      - name: Testing Code
        run: |
          echo "Running Tests"
          pytest

      - name: "Packaging artifacts"
        run: |
          mkdir -p dist
          zip dist/my_app.zip scripts/

      - name: "Uploading artifacts"
        if: ${{success()}}
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: dist/my_app.zip
