name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  test_hello_script:
    name: Test Hello Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - name: Run test
        run: python -m pytest day1/test_hello.py
